# config.yaml

database:
  dbUser: "{{DB_USER}}"
  dbPassword: "{{DB_PASSWORD}}"
  dbHost: "{{DB_HOST}}"
  dbPort: "{{DB_PORT}}"

api:
  paymentGatewayKey: "{{PAYMENT_GAYWAY_KEY}}"  
  smsProviderKey: "{{SMS_PROVIDER_KEY}}" 
  internalServiceToken: "{{INTERNAL_SERVICE_TOKEN}}"  
  analyticsIntegrationKey: "{{ANALYTICS_INTEGRATION_KEY}}"  

thirdParty:
  awsAccessKey: "{{AWS_ACCESS_KEY}}"
  awsSecretKey: "{{AWS_SECRET_KEY}}"
  analyticsKey: "{{ANALYTICS_KEY}}"
  smsServiceKey: "{{SMS_SERVICE_KEY}}"

